import Head from 'next/head'
import { useEffect, useState } from 'react'
import { forEach, size, map } from 'lodash'
import InfiniteScroll from 'react-infinite-scroll-component'
import { useRouter } from 'next/router'
import { Container, Grid, Card, Title, Text, Flex } from '@mantine/core'

import { RootState, postsApi, valorantApi } from '@/store'
import PlayerCard from '@/components/Players/PlayerCard'
import PlayersListComponent from '@/components/Players/PlayersList'
import PostsListComponent from '@/components/PostsList'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Grid>
            {/* Posts List */}
            <Grid.Col span={8}>
              <Title order={3}>Posts</Title>
              <PostsListComponent/>
            </Grid.Col>
            <Grid.Col span={4}>
              <Title order={3}>Leaderboard</Title>
              <PlayersListComponent/>
            </Grid.Col>
          </Grid>
        </Container>
      </main>
    </>
  )
}
